-- Install mason first, since it grabs stuff used by other plugins.
require("plugins.mason")

require("plugins.flash")
require("plugins.gitsigns")
require("plugins.gruvbox-material")
require("plugins.indent-blankline")
require("plugins.lualine")
require("plugins.mini-completion")
require("plugins.nvim-dap")
require("plugins.nvim-lspconfig")
require("plugins.nvim-treesitter")
require("plugins.nvim-unception")
require("plugins.telescope")
require("plugins.vim-auto-nohlsearch")
require("plugins.vim-bufdir")
require("plugins.vim-smoothie")
require("plugins.which-key")
